export const UserConst = {
  ON_USERS_LIST_LOADING: "ON_USERS_LIST_LOADING",
  ON_USERS_LIST_FAIL: "ON_USERS_LIST_FAIL",
  ON_USERS_LIST_SUCCESS: "ON_USERS_LIST_SUCCESS",
  ON_USER_ADD_LOADING: "ON_USER_ADD_LOADING",
  ON_USER_ADD_SUCCESS: "ON_USER_ADD",
  ON_USER_ADD_FAIL: "ON_USER_ADD_FAIL",
  ON_USER_REMOVE: "ON_USER_REMOVE",
  ON_USER_LOGIN:"LOGIN",
  ON_USER_LOGOUT:"LOGOUT"
};
