export const UserConst = {
  ON_USERS_LIST_LOADING: "ON_USERS_LIST_LOADING",
  ON_USERS_LIST_FAIL: "ON_USERS_LIST_FAIL",
  ON_USERS_LIST_SUCCESS: "ON_USERS_LIST_SUCCESS",
  ON_USER_REMOVE: "ON_USER_REMOVE",
};
